---
title: "Intallation of packages"
output: 
  github_document: 
  toc: true
  toc_depth: 2
---


#update VM configuration
``` {bash}
sudo apt-get update -y 
sudo apt-get install -y libbz2-dev
sudo apt-get install -y liblzma-dev
```


#package install

Following instruction on https://benjjneb.github.io/dada2/dada-installation.html
Installation de BiocManager puis de dad2

```{r package install}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = '3.11')
BiocManager::install("dada2", version = "3.11")
```

Installation de Phangorn
```{r}
BiocManager::install("phangorn")
```

Installation de phyloseq par BiocManager
```{r}
if(!requireNamespace("BiocManager"))
  install.packages("BiocManager")
BiocManager::install(version='3.11')
BiocManager::install("phyloseq")
```

```{r}
BiocManager::install("phyloseq")
```


```{r}
library(phyloseq); packageVersion("phyloseq")
```


```{bash}
sudo apt-get install -y libglpk-dev
```


```{r}
BiocManager::install("phyloseq")
```

Installation de gridExtra
```{r}
install.packages("gridExtra")
```


Installation de grid.arrange
```{r}
install.packages("grid.arrange")
```

 
```{r}
.cran_packages <- c( "shiny","miniUI", "caret", "pls", "e1071", "ggplot2", "randomForest", "dplyr", "ggrepel", "nlme", "devtools",
                  "reshape2", "PMA", "structSSI", "ade4",
                  "ggnetwork", "intergraph", "scales")
.github_packages <- c("jfukuyama/phyloseqGraphTest")
.bioc_packages <- c("genefilter", "impute")
```



```{r}
install.packages(.cran_pacjages)
devtools::install_github(.github_packages)
BiocManager::install(.bioc_packages)
```

```{r}
BiocManager::install("DESeq2")
```


```{bash}
wget https://cran.r-project.org/src/contrib/Archive/structSSI/structSSI_1.1.1.tar.gz
```

```{r}
library(devtools)
install_local("./structSSI_1.1.1.tar.gz")
```

```{r}
install.packages("markdown")
```

```{r}
install.packages("knitr")
```

GOOD: 
```{r}
library("knitr")
library("BiocManager")
.cran_packages <- c("ggplot2", "gridExtra")
.bioc_packages <- c("dada2", "phyloseq", "DECIPHER", "phangorn")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)) {
   BiocManager::install(.bioc_packages[!.inst], ask = F)
}
# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)
```

